"""
Task Plan Validators — LLM Hallucination Guard (Layer 2).

Validates the structured task plan generated by the LLM to ensure
it only uses whitelisted action primitives, respects all constraints,
and contains no hallucinated data.
"""

import re
from typing import Any, Dict, List, Optional, Set

from utils.logger import log


# ─── Whitelisted Action Primitives ───────────────────────────
ALLOWED_ACTIONS: Set[str] = {
    "move_home",
    "move_to_pose",
    "open_gripper",
    "close_gripper",
    "pick_object",
    "place_object",
    "verify_grasp",
    "request_perception_update",
}

# Actions that require specific parameters
ACTION_PARAMS = {
    "move_home": [],
    "move_to_pose": ["x", "y", "z"],   # rx, ry, rz are optional
    "open_gripper": [],
    "close_gripper": [],
    "pick_object": ["object_id", "x", "y", "z"],
    "place_object": ["object_id", "x", "y", "z"],
    "verify_grasp": [],
    "request_perception_update": [],
}

# Default workspace bounds (matches actual UR10 + gantry reach)
DEFAULT_WORKSPACE_BOUNDS = {
    "x_min": -1.5, "x_max": 2.0,
    "y_min": -1.5, "y_max": 1.5,
    "z_min": -0.1, "z_max": 1.5,
}

# Joint angle patterns to reject (hallucination detection)
JOINT_ANGLE_PATTERNS = [
    r"joint_angle",
    r"joint_position",
    r"joint_velocity",
    r"motor_command",
    r"torque",
    r"\bq\d\b",          # q0, q1, q2, ...
    r"\bj\d\b",          # j0, j1, j2, ...
    r"radians?",
]


class PlanValidationError(Exception):
    """
    Exception raised when a task plan fails validation.

    Attributes
    ----------
    errors : list of str
        Detailed list of validation errors.
    plan : dict
        The invalid plan that caused the error.
    """

    def __init__(self, errors: List[str], plan: Optional[Dict] = None):
        self.errors = errors
        self.plan = plan
        message = f"Plan validation failed with {len(errors)} error(s): {'; '.join(errors[:3])}"
        if len(errors) > 3:
            message += f"... and {len(errors) - 3} more"
        super().__init__(message)


def validate_task_plan(
    plan: Dict[str, Any],
    scene_objects: Optional[List[str]] = None,
    workspace_bounds: Optional[Dict[str, float]] = None,
    max_steps: int = 50,
) -> Dict[str, Any]:
    """
    Validate a complete task plan from the LLM.

    Parameters
    ----------
    plan : dict
        The parsed task plan with ``task_summary``, ``total_steps``, and ``plan``.
    scene_objects : list of str, optional
        List of valid object_ids from the current scene perception.
    workspace_bounds : dict, optional
        Workspace bounds for coordinate validation.
    max_steps : int
        Maximum allowed number of steps (anti-hallucination limit).

    Returns
    -------
    dict
        The validated (and potentially cleaned) plan.

    Raises
    ------
    PlanValidationError
        If the plan contains any invalid elements.
    """
    errors = []
    bounds = workspace_bounds or DEFAULT_WORKSPACE_BOUNDS

    # ── Structure validation ─────────────────────────────────
    if not isinstance(plan, dict):
        raise PlanValidationError(["Plan must be a dict"], plan)

    if "plan" not in plan:
        errors.append("Missing 'plan' key in task plan")

    if "task_summary" not in plan:
        plan["task_summary"] = "No summary provided"

    steps = plan.get("plan", [])
    if not isinstance(steps, list):
        raise PlanValidationError(["'plan' must be a list of steps"], plan)

    if len(steps) == 0:
        errors.append("Plan contains zero steps")

    # ── Step count limit (anti-hallucination) ─────────────────
    if len(steps) > max_steps:
        errors.append(
            f"Plan has {len(steps)} steps — exceeds maximum of {max_steps}. "
            "Likely a hallucinated loop."
        )

    # ── Start/End with move_home ──────────────────────────────
    if steps:
        first_action = steps[0].get("action", "")
        if first_action != "move_home":
            errors.append(
                f"Plan must START with move_home(), but starts with '{first_action}'"
            )

        last_action = steps[-1].get("action", "")
        if last_action != "move_home":
            errors.append(
                f"Plan must END with move_home(), but ends with '{last_action}'"
            )

    # ── Per-step validation ───────────────────────────────────
    for i, step in enumerate(steps):
        step_num = step.get("step", i + 1)
        action = step.get("action", "")
        params = step.get("params", {})

        # 1. Action whitelist
        if action not in ALLOWED_ACTIONS:
            errors.append(
                f"Step {step_num}: action '{action}' is not in the allowed "
                f"primitives list: {sorted(ALLOWED_ACTIONS)}"
            )
            continue

        # 2. Required parameters
        required = ACTION_PARAMS.get(action, [])
        for param in required:
            if param not in params:
                errors.append(
                    f"Step {step_num} ({action}): missing required parameter '{param}'"
                )

        # 3. Coordinate bounds check (for actions with x, y, z)
        if action in ("move_to_pose", "pick_object", "place_object"):
            for axis in ("x", "y", "z"):
                if axis in params:
                    val = params[axis]
                    try:
                        val = float(val)
                    except (ValueError, TypeError):
                        errors.append(
                            f"Step {step_num} ({action}): '{axis}' = {val} is not numeric"
                        )
                        continue

                    lo = bounds.get(f"{axis}_min", -float("inf"))
                    hi = bounds.get(f"{axis}_max", float("inf"))
                    if val < lo or val > hi:
                        errors.append(
                            f"Step {step_num} ({action}): {axis}={val:.3f} "
                            f"outside workspace bounds [{lo}, {hi}]"
                        )

        # 4. Object ID validation
        if action in ("pick_object", "place_object") and scene_objects is not None:
            obj_id = params.get("object_id", "")
            if obj_id and obj_id not in scene_objects:
                errors.append(
                    f"Step {step_num} ({action}): object_id '{obj_id}' "
                    f"not found in scene objects {scene_objects}"
                )

        # 5. Raw joint angle detection (hallucination guard)
        params_str = str(params).lower()
        for pattern in JOINT_ANGLE_PATTERNS:
            if re.search(pattern, params_str):
                errors.append(
                    f"Step {step_num} ({action}): params contain prohibited "
                    f"joint-level data (matched pattern: '{pattern}')"
                )
                break

    # ── Sequence constraint: open_gripper → pick_object → verify_grasp ──
    for i, step in enumerate(steps):
        action = step.get("action", "")

        if action == "pick_object":
            # Must be preceded by open_gripper
            if i == 0 or steps[i - 1].get("action") != "open_gripper":
                errors.append(
                    f"Step {step.get('step', i+1)}: pick_object must be "
                    f"preceded by open_gripper()"
                )

            # Must be followed by verify_grasp
            if i >= len(steps) - 1 or steps[i + 1].get("action") != "verify_grasp":
                errors.append(
                    f"Step {step.get('step', i+1)}: pick_object must be "
                    f"followed by verify_grasp()"
                )

    # ── Raise if any errors ───────────────────────────────────
    if errors:
        raise PlanValidationError(errors, plan)

    # ── Fix total_steps count ─────────────────────────────────
    plan["total_steps"] = len(steps)

    log.info(f"Task plan validated: {len(steps)} steps, 0 errors")
    return plan
